// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mtfpcjfyfdgqhlycmcfx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im10ZnBjamZ5ZmRncWhseWNtY2Z4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDgyMjE4NTksImV4cCI6MjA2Mzc5Nzg1OX0.7a65OSxKuDL1aoZ0pVJB1W7qEaV1-co_tq-2OfeTyrs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);